# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 51d681b328f968728e0509927052597c84cd3e2b769c73148c229cec54782e911f4b1f31e1ecedeb8c3ed3d1c2cffe52145b3a236fb023d38f7048f7e414a5f5

test:
  secret_key_base: 4298b6d59e3298217e76e1d710da11f9094bd00b200631d0e6c7e58d45a7b566097d9c7c9a76d051731a218a606d0e952bfa120c25642227049e3e6b68129b35

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
